"use server";
import { addDays, startOfWeek } from "date-fns";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { requireProfile } from "@/lib/session";
const uuid=z.uuid();
export async function saveTemplate(input:unknown){const parsed=z.object({id:uuid.optional(),name:z.string().min(1).max(200),description:z.string().max(2000).optional(),weeks:z.number().int().min(1).max(52)}).safeParse(input);if(!parsed.success)return{ok:false,error:parsed.error.issues[0]?.message};try{const db=await createClient();const me=await requireProfile();const row={name:parsed.data.name,description:parsed.data.description,weeks:parsed.data.weeks,author_id:me.id};const query=parsed.data.id?db.from("plan_templates").update(row).eq("id",parsed.data.id):db.from("plan_templates").insert(row);const {data,error}=await query.select("id").single();if(error)throw error;revalidatePath("/templates");return{ok:true,id:data.id};}catch(error){return{ok:false,error:error instanceof Error?error.message:"Could not save plan"}}}
export async function deleteTemplate(id:string){const db=await createClient();const {error}=await db.from("plan_templates").delete().eq("id",id);revalidatePath("/templates");return error?{ok:false,error:error.message}:{ok:true};}
export async function saveTemplateItem(input:Record<string,unknown>){try{const db=await createClient();const {data,error}=await db.from("plan_template_items").upsert(input).select("id").single();if(error)throw error;return{ok:true,id:data.id};}catch(error){return{ok:false,error:error instanceof Error?error.message:"Could not save item"}}}
export async function deleteTemplateItem(id:string){const db=await createClient();const {error}=await db.from("plan_template_items").delete().eq("id",id);return error?{ok:false,error:error.message}:{ok:true};}
export async function applyTemplate(templateId:string,athleteId:string,startDate:string){try{const db=await createClient();const me=await requireProfile();const {data:items,error}=await db.from("plan_template_items").select("*").eq("template_id",templateId);if(error)throw error;const monday=startOfWeek(new Date(`${startDate}T12:00:00`),{weekStartsOn:1});const rows=(items??[]).map((item)=>({athlete_id:athleteId,created_by:me.id,date:addDays(monday,(item.week-1)*7+item.day_of_week-1).toISOString().slice(0,10),title:item.title,type:item.type,structure:item.structure,planned_duration_sec:item.planned_duration_sec,planned_load:item.planned_load,coach_notes:item.notes}));if(rows.length){const result=await db.from("workouts").insert(rows);if(result.error)throw result.error;}revalidatePath("/");return{ok:true};}catch(error){return{ok:false,error:error instanceof Error?error.message:"Could not apply plan"}}}
