export function LoadExplainer() {
  return <details className="card"><summary className="cursor-pointer font-black">How to read this chart</summary><div className="mt-4 space-y-5 text-sm leading-6 text-ink-200">
    <section><h3 className="font-black text-white">1. Daily load — grey bars</h3><p>Each bar is the stress from sessions completed that day. Load combines duration with average heart rate as a percentage of your personal maximum heart rate. Sustaining the same heart-rate percentage for longer creates more load, while higher intensity rises faster.</p><p className="mt-2">When calories are entered, they adjust that estimate by up to 25%. The app compares calories with a neutral reference of 600 kcal per hour. This keeps watch estimates useful without letting an inaccurate calorie reading dominate the score.</p></section>
    <section><h3 className="font-black text-brand-400">2. Fitness — yellow area</h3><p>A slow 42-day average of daily load. It rises after consistent training and falls gradually during rest. Think of it as your longer-term capacity, not a measurement of speed or strength.</p></section>
    <section><h3 className="font-black text-red-400">3. Fatigue — red line</h3><p>A faster 7-day average. It jumps after hard days and drops quickly when you recover. It represents recent training stress.</p></section>
    <section><h3 className="font-black text-sky-400">4. Form — blue line</h3><p>Yesterday’s fitness minus yesterday’s fatigue. Negative form means recent work is higher than your longer-term fitness; positive form means fatigue has fallen and you are fresher. Today’s workout affects tomorrow’s form, avoiding a same-day illusion.</p></section>
    <div className="grid gap-2 sm:grid-cols-4"><span className="rounded-lg bg-sky-950 p-2 text-sky-300"><b>Fresh</b><br/>above 15</span><span className="rounded-lg bg-emerald-950 p-2 text-emerald-300"><b>Neutral</b><br/>−10 to 15</span><span className="rounded-lg bg-amber-950 p-2 text-amber-300"><b>Building</b><br/>−30 to −10</span><span className="rounded-lg bg-red-950 p-2 text-red-300"><b>Overreaching</b><br/>below −30</span></div>
    <p><b className="text-white">Weekly ramp</b> compares this week’s load with last week. A rise above 15% is a warning to check sleep, soreness and session quality—not an automatic instruction to stop.</p>
  </div></details>;
}
