"use client";

import { useState } from "react";
import { STATIONS, type Division } from "@/lib/hyrox";
import { buildHalfSimulation, buildRaceSimulation, describeQuantity, stepTitle, type WorkoutStep, type WorkoutStructure } from "@/lib/workout";

const id = () => crypto.randomUUID();
const STRENGTH_EXERCISES = ["Back Squat", "Front Squat", "Deadlift", "Romanian Deadlift", "Bench Press", "Overhead Press", "Pull-up", "Walking Lunge", "Bulgarian Split Squat", "Box Step-up", "Kettlebell Swing", "Thruster"];
export function StructureEditor({ value, onChange, division = "men_open" }: { value: WorkoutStructure; onChange: (value: WorkoutStructure) => void; division?: Division }) {
  const [exercise, setExercise] = useState(STRENGTH_EXERCISES[0]);
  const [customExercise, setCustomExercise] = useState("");
  const updateStep = (blockIndex: number, stepIndex: number, patch: Partial<WorkoutStep>) => { const blocks = structuredClone(value.blocks); blocks[blockIndex].steps[stepIndex] = { ...blocks[blockIndex].steps[stepIndex], ...patch }; onChange({ blocks }); };
  const add = (kind: WorkoutStep["kind"], station?: WorkoutStep["station"]) => { const blocks = value.blocks.length ? structuredClone(value.blocks) : [{ id: id(), rounds: 1, label: "Main set", steps: [] }]; blocks.at(-1)!.steps.push({ id: id(), kind, station, mode: kind === "rest" ? "duration" : station === "wall_balls" || kind === "strength" ? "reps" : "distance", value: kind === "run" ? 1000 : kind === "rest" ? 60 : station === "wall_balls" ? 100 : 10, rpe: kind === "rest" ? undefined : 7 }); onChange({ blocks }); };
  const addExercise = () => {
    const label = exercise === "custom" ? customExercise.trim() : exercise;
    if (!label) return;
    const blocks = value.blocks.length ? structuredClone(value.blocks) : [{ id: id(), rounds: 1, label: "Main set", steps: [] }];
    blocks.at(-1)!.steps.push({ id: id(), kind: "strength", label, mode: "reps", value: 10, rpe: 7 });
    onChange({ blocks });
    setCustomExercise("");
  };
  return <div className="space-y-4"><div className="flex flex-wrap gap-2"><button type="button" className="chip" onClick={() => onChange(buildHalfSimulation(division))}>½ Half sim</button><button type="button" className="chip" onClick={() => onChange(buildRaceSimulation(division))}>🔥 Full sim</button><button type="button" className="chip" onClick={() => onChange({ blocks: [] })}>Clear</button></div>
    {value.blocks.map((block, bi) => <section key={block.id} className="card"><div className="flex gap-2"><input className="input" value={block.label ?? ""} aria-label="Block name" onChange={(e) => { const blocks = structuredClone(value.blocks); blocks[bi].label = e.target.value; onChange({ blocks }); }} /><label className="w-24 text-sm text-ink-400">Rounds<input className="input mt-1" type="number" min="1" max="99" value={block.rounds} onChange={(e) => { const blocks = structuredClone(value.blocks); blocks[bi].rounds = Number(e.target.value); onChange({ blocks }); }} /></label></div>
      <div className="mt-3 space-y-2">{block.steps.map((step, si) => <details key={step.id} className="rounded-xl border border-ink-700 bg-ink-900 p-3"><summary className="cursor-pointer font-bold">{stepTitle(step)} <span className="ml-2 font-normal text-ink-400">{describeQuantity(step)} · RPE {step.rpe ?? "—"}</span></summary><div className="mt-4 grid gap-3 sm:grid-cols-4">{step.kind === "strength" && <label className="sm:col-span-4"><span className="label">Exercise name</span><input className="input" value={step.label ?? ""} placeholder="e.g. Back Squat" onChange={(e) => updateStep(bi, si, { label: e.target.value })} /></label>}<label><span className="label">Measure</span><select className="input" value={step.mode} onChange={(e) => updateStep(bi, si, { mode: e.target.value as WorkoutStep["mode"] })}><option value="distance">Distance</option><option value="duration">Duration</option><option value="reps">Reps</option><option value="calories">Calories</option></select></label><label><span className="label">Amount</span><input className="input" type="number" min="0" value={step.value} onChange={(e) => updateStep(bi, si, { value: Number(e.target.value) })} /></label><label><span className="label">Load kg</span><input className="input" type="number" min="0" step="0.5" value={step.loadKg ?? ""} onChange={(e) => updateStep(bi, si, { loadKg: e.target.value ? Number(e.target.value) : undefined })} /></label><label><span className="label">Rest sec</span><input className="input" type="number" min="0" value={step.restSec ?? ""} onChange={(e) => updateStep(bi, si, { restSec: Number(e.target.value) || undefined })} /></label><label className="sm:col-span-4"><span className="label">RPE {step.rpe ?? 5}</span><input className="w-full" type="range" min="1" max="10" value={step.rpe ?? 5} onChange={(e) => updateStep(bi, si, { rpe: Number(e.target.value) })} /></label><div className="flex gap-2 sm:col-span-4"><button type="button" className="btn-ghost" disabled={si === 0} onClick={() => { const blocks = structuredClone(value.blocks); [blocks[bi].steps[si - 1], blocks[bi].steps[si]] = [blocks[bi].steps[si], blocks[bi].steps[si - 1]]; onChange({ blocks }); }}>↑</button><button type="button" className="btn-ghost" disabled={si === block.steps.length - 1} onClick={() => { const blocks = structuredClone(value.blocks); [blocks[bi].steps[si + 1], blocks[bi].steps[si]] = [blocks[bi].steps[si], blocks[bi].steps[si + 1]]; onChange({ blocks }); }}>↓</button><button type="button" className="btn-danger ml-auto" onClick={() => { const blocks = structuredClone(value.blocks); blocks[bi].steps.splice(si, 1); onChange({ blocks }); }}>Remove</button></div></div></details>)}</div></section>)}
    <div className="card space-y-4"><div><span className="label">Add running, rest or a Hyrox station</span><div className="flex flex-wrap gap-2"><button type="button" className="chip" onClick={() => add("run")}>🏃 Run</button><button type="button" className="chip" onClick={() => add("rest")}>⏱ Rest</button>{STATIONS.map((station) => <button type="button" className="chip" key={station.id} onClick={() => add("station", station.id)}>{station.emoji} {station.short}</button>)}</div></div><div className="border-t border-ink-700 pt-4"><span className="label">Add strength exercise</span><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><select className="input" value={exercise} onChange={(e) => setExercise(e.target.value)}><optgroup label="Common exercises">{STRENGTH_EXERCISES.map((item) => <option value={item} key={item}>{item}</option>)}</optgroup><option value="custom">Custom exercise…</option></select><button type="button" className="btn-primary" onClick={addExercise}>＋ Add exercise</button></div>{exercise === "custom" && <input className="input mt-2" value={customExercise} onChange={(e) => setCustomExercise(e.target.value)} placeholder="Enter exercise name" />}</div></div>
  </div>;
}
