create type public.member_role as enum ('athlete','coach');
create type public.hyrox_division as enum ('men_open','women_open','men_pro','women_pro');
create type public.workout_type as enum ('run','erg','strength','hyrox_sim','compromised','recovery','other');
create type public.workout_status as enum ('planned','completed','skipped');
create type public.pb_metric as enum ('time_sec','reps','max_kg');

create table public.allowed_members (email text primary key check (email = lower(email)), display_name text not null, role public.member_role not null default 'athlete', invited_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null unique, display_name text not null, role public.member_role not null default 'athlete', division public.hyrox_division not null default 'men_open', threshold_pace_sec_per_km integer not null default 270 check (threshold_pace_sec_per_km between 120 and 900), weight_kg numeric check (weight_kg > 0), emoji text not null default '💪', goal_race_name text, goal_race_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workouts (id uuid primary key default gen_random_uuid(), athlete_id uuid not null references public.profiles(id) on delete cascade, created_by uuid not null references public.profiles(id), date date not null, title text not null check (char_length(title) between 1 and 200), type public.workout_type not null, structure jsonb not null default '{"blocks":[]}'::jsonb, planned_duration_sec integer not null default 0 check (planned_duration_sec >= 0), planned_load integer not null default 0 check (planned_load >= 0), status public.workout_status not null default 'planned', coach_notes text, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index workouts_athlete_date_idx on public.workouts(athlete_id,date); create index workouts_date_idx on public.workouts(date);
create table public.workout_results (id uuid primary key default gen_random_uuid(), workout_id uuid not null unique references public.workouts(id) on delete cascade, athlete_id uuid not null references public.profiles(id) on delete cascade, date date not null, duration_sec integer not null check (duration_sec > 0), calories integer check (calories > 0), rpe integer not null check (rpe between 1 and 10), feeling integer check (feeling between 1 and 5), load integer not null check (load >= 0), notes text, step_results jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.station_results (id uuid primary key default gen_random_uuid(), athlete_id uuid not null references public.profiles(id) on delete cascade, workout_id uuid references public.workouts(id) on delete set null, date date not null, station text not null, metric public.pb_metric not null, value numeric not null check (value > 0), load_kg numeric, notes text, created_at timestamptz not null default now());
create table public.comments (id uuid primary key default gen_random_uuid(), workout_id uuid not null references public.workouts(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete cascade, body text not null check (char_length(body) between 1 and 2000), created_at timestamptz not null default now());
create table public.plan_templates (id uuid primary key default gen_random_uuid(), name text not null, description text, weeks integer not null check (weeks between 1 and 52), author_id uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.plan_template_items (id uuid primary key default gen_random_uuid(), template_id uuid not null references public.plan_templates(id) on delete cascade, week integer not null check (week >= 1), day_of_week integer not null check (day_of_week between 1 and 7), title text not null, type public.workout_type not null, structure jsonb not null default '{"blocks":[]}'::jsonb, planned_duration_sec integer not null default 0, planned_load integer not null default 0, notes text);

create function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
create trigger workouts_touch before update on public.workouts for each row execute function public.touch_updated_at();
create trigger workout_results_touch before update on public.workout_results for each row execute function public.touch_updated_at();

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare member public.allowed_members%rowtype; begin select * into member from public.allowed_members where email=lower(new.email); if not found then raise exception 'Email is not on the HyroxBros allowlist'; end if; insert into public.profiles(id,email,display_name,role) values(new.id,lower(new.email),member.display_name,member.role); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create function public.is_member() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid()); $$;
create function public.is_coach() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='coach'); $$;

alter table public.allowed_members enable row level security; alter table public.profiles enable row level security; alter table public.workouts enable row level security; alter table public.workout_results enable row level security; alter table public.station_results enable row level security; alter table public.comments enable row level security; alter table public.plan_templates enable row level security; alter table public.plan_template_items enable row level security;
create policy "members read profiles" on public.profiles for select using (public.is_member()); create policy "self updates profile" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy "members read workouts" on public.workouts for select using(public.is_member()); create policy "members create workouts" on public.workouts for insert with check(public.is_member() and created_by=auth.uid()); create policy "members update workouts" on public.workouts for update using(public.is_member()) with check(public.is_member()); create policy "owners delete workouts" on public.workouts for delete using(athlete_id=auth.uid() or created_by=auth.uid() or public.is_coach());
create policy "members read results" on public.workout_results for select using(public.is_member()); create policy "athlete writes results" on public.workout_results for all using(athlete_id=auth.uid() or public.is_coach()) with check(athlete_id=auth.uid() or public.is_coach());
create policy "members read station results" on public.station_results for select using(public.is_member()); create policy "athlete writes station results" on public.station_results for all using(athlete_id=auth.uid() or public.is_coach()) with check(athlete_id=auth.uid() or public.is_coach());
create policy "members read comments" on public.comments for select using(public.is_member()); create policy "authors add comments" on public.comments for insert with check(public.is_member() and author_id=auth.uid()); create policy "authors edit comments" on public.comments for update using(author_id=auth.uid()) with check(author_id=auth.uid()); create policy "authors delete comments" on public.comments for delete using(author_id=auth.uid() or public.is_coach());
create policy "members read templates" on public.plan_templates for select using(public.is_member()); create policy "authors write templates" on public.plan_templates for all using(author_id=auth.uid() or public.is_coach()) with check(author_id=auth.uid() or public.is_coach());
create policy "members read template items" on public.plan_template_items for select using(public.is_member()); create policy "authors write template items" on public.plan_template_items for all using(exists(select 1 from public.plan_templates t where t.id=template_id and (t.author_id=auth.uid() or public.is_coach()))) with check(exists(select 1 from public.plan_templates t where t.id=template_id and (t.author_id=auth.uid() or public.is_coach())));
create policy "coaches read allowlist" on public.allowed_members for select using(public.is_coach()); create policy "coaches write allowlist" on public.allowed_members for all using(public.is_coach()) with check(public.is_coach());
